packages:
  - src/**
  - "!**/test-data/**"
  - "!**/dist/**"

# https://pnpm.io/catalogs
catalog:
  # Trails core packages
  # https://github.com/open-pioneer/trails-core-packages
  "@open-pioneer/base-theme": 4.5.0-dev.20260209115911
  "@open-pioneer/core": 4.5.0-dev.20260209115911
  "@open-pioneer/http": 4.5.0-dev.20260209115911
  "@open-pioneer/integration": 4.5.0-dev.20260209115911
  "@open-pioneer/local-storage": 4.5.0-dev.20260209115911
  "@open-pioneer/notifier": 4.5.0-dev.20260209115911
  "@open-pioneer/react-utils": 4.5.0-dev.20260209115911
  "@open-pioneer/reactivity": 4.5.0-dev.20260209115911
  "@open-pioneer/runtime": 4.5.0-dev.20260209115911
  "@open-pioneer/test-utils": 4.5.0-dev.20260209115911
  "@open-pioneer/chakra-snippets": 4.5.0-dev.20260209115911

  "@chakra-ui/react": ^3.32.0
  "@chakra-ui/cli": ^3.32.0
  "@conterra/reactivity-core": ^0.8.1
  "@conterra/reactivity-events": ^0.8.1
  "@emotion/cache": ^11.14.0
  "@emotion/react": ^11.14.0
  "@emotion/styled": ^11.14.1
  "@formatjs/intl": ^4.1.2
  "@tanstack/react-table": ^8.21.3
  classnames: ^2.5.1
  framer-motion: ^12.33.0
  html2canvas: ^1.4.1
  jspdf: ^4.1.0
  ol-mapbox-style: ^13.2.0
  ol: ^10.7.0
  proj4: ^2.20.2
  react-dom: ^19.2.4
  react-icons: ^5.5.0
  react-use: ^17.6.0
  react: ^19.2.4
  uuid: ^13.0.0

  # Devtools
  "@changesets/cli": ^2.29.8
  "@open-pioneer/build-package-cli": ^3.0.7
  "@open-pioneer/build-support": ^3.0.5
  "@open-pioneer/check-pnpm-duplicates": ^0.2.6
  "@open-pioneer/vite-plugin-pioneer": ^5.1.0
  "@testing-library/dom": ^10.4.1
  "@testing-library/jest-dom": ^6.9.1
  "@testing-library/react": ^16.3.2
  "@testing-library/user-event": ^14.6.1
  "@types/js-yaml": ^4.0.9
  "@types/jsdom": ^27.0.0
  "@types/node": ^20.19.32
  "@types/react": ^19.2.13
  "@types/react-dom": ^19.2.3
  "@typescript-eslint/parser": ^8.54.0
  "@vitejs/plugin-react-swc": ^4.2.3
  eslint: ^9.39.2
  "@eslint/js": ^9.39.2
  "typescript-eslint": ^8.54.0
  eslint-config-prettier: ^10.1.8
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-headers: ^1.3.3
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-unused-imports: ^4.3.0
  fast-glob: ^3.3.3
  handlebars: ^4.7.8
  happy-dom: ^20.5.0
  husky: ^9.1.7
  js-yaml: ^4.1.1
  jsdom: ^28.0.0
  lint-staged: ^16.2.7
  prettier: ^3.8.1
  resize-observer-polyfill: ^1.5.1
  rimraf: ^6.1.2
  sass: ^1.97.3
  tsx: ^4.21.0
  typedoc: ^0.28.16
  typescript: ^5.9.3
  vite: ^7.3.1
  vite-plugin-eslint: ^1.8.1
  vitest: ^4.0.18
  zx: ^8.8.5

auditConfig:
  ignoreCves: []

# Install older versions by default
resolutionMode: "lowest-direct"

# Configure a release cooldown
minimumReleaseAge: 4320 # 3 days in minutes
minimumReleaseAgeExclude:
  - "@open-pioneer/*"
  - "@conterra/*"
  - "@isaacs/brace-expansion@5.0.1" # see overrides

overrides:
  # https://github.com/advisories/GHSA-7h2j-956f-4vf2
  "@isaacs/brace-expansion@<=5.0.0": "^5.0.1"

  # https://github.com/advisories/GHSA-5j98-mcp5-4vw2
  "glob@>=10.x <= 11.0.3": "^11.1.0"

  # We don't actually use the babel plugin.
  # The babel runtime is also not used as a production dependency.
  # See e.g. https://github.com/emotion-js/emotion/issues/2371
  "@emotion/react>@emotion/babel-plugin": "-"
  "@emotion/styled>@emotion/babel-plugin": "-"
  "@emotion/react>@babel/runtime": "-"
  "@emotion/styled>@babel/runtime": "-"

  # Just to get rid of some duplicate dependencies
  "source-map@<0.6.1": ">=0.6.1"
  "stylis@<4.3.5": ">= 4.3.5"
  "regenerator-runtime@<=0.13.11": "^0.14.0"
  "csstype@<3.2.3": ">=3.2.3"

  # Ensure patched packages have the expected version (patch was tested with this version):
  "@ark-ui/react": "5.31.0"

allowUnusedPatches: true
ignorePatchFailures: false
patchedDependencies:
  # Ensure all portals are mounted under `.pioneer-root` div
  "@ark-ui/react@*": "patches/@ark-ui__react.patch"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild

ignoredBuiltDependencies:
  # Seems to work without build scripts; may revisit later if actually needed.
  - core-js
  - unrs-resolver

# Workaround for current problems regarding our vite plugin + vite's optimizeDeps feature
shamefullyHoist: true

# Workspace root itself depends on runtime, and all packages (including runtime) have a dev dependency on workspace root
# for shared scripts.
ignoreWorkspaceCycles: true

linkWorkspacePackages: false
strictPeerDependencies: true
