packages:
  - src/**
  - support/disabled-package
  - "!**/test-data/**"
  - "!**/dist/**"
  - .

# Shared version expressions (yaml anchors).
# This is a yaml feature and is not interpreted by pnpm directly.
__versions:
  - &react_version ^18.3.1
  - &core_packages_version ^2.3.0

# https://pnpm.io/catalogs
catalog:
  # Trails core packages
  # https://github.com/open-pioneer/trails-core-packages
  "@open-pioneer/base-theme": *core_packages_version
  "@open-pioneer/chakra-integration": *core_packages_version
  "@open-pioneer/core": *core_packages_version
  "@open-pioneer/http": *core_packages_version
  "@open-pioneer/integration": *core_packages_version
  "@open-pioneer/local-storage": *core_packages_version
  "@open-pioneer/notifier": *core_packages_version
  "@open-pioneer/react-utils": *core_packages_version
  "@open-pioneer/reactivity": *core_packages_version
  "@open-pioneer/runtime": *core_packages_version
  "@open-pioneer/test-utils": *core_packages_version

  "@chakra-ui/icons": ^2.1.1
  "@chakra-ui/react": ^2.8.2
  "@chakra-ui/system": ^2.6.2
  "@changesets/cli": ^2.27.8
  "@conterra/reactivity-core": ^0.4.2
  "@emotion/cache": ^11.13.0
  "@emotion/react": ^11.13.0
  "@emotion/styled": ^11.13.0
  "@formatjs/intl": ^2.10.4
  "@maplibre/maplibre-gl-style-spec": ^20.1.1
  "@open-pioneer/build-package-cli": ^2.1.0
  "@open-pioneer/build-support": ^2.0.2
  "@open-pioneer/vite-plugin-pioneer": ^3.0.4
  "@open-pioneer/check-pnpm-duplicates": "^0.1.0"
  "@tanstack/react-table": "^8.11.6"
  "@testing-library/dom": ^10.0.0
  "@testing-library/jest-dom": ^6.4.7
  "@testing-library/react": ^16.0.0
  "@testing-library/user-event": ^14.5.2
  "@types/js-yaml": ^4.0.9
  "@types/jsdom": ^21.1.7
  "@types/node": ^18.19.41
  "@types/proj4": "^2.5.2"
  "@types/react": ^18.3.3
  "@types/react-dom": ^18.3.0
  "@types/uuid": ^10.0.0
  "@typescript-eslint/eslint-plugin": ^7.17.0
  "@typescript-eslint/parser": ^7.17.0
  "@vitejs/plugin-react-swc": ^3.7.0
  chakra-react-select: ^4.7.6
  classnames: ^2.3.2
  eslint: ^8.57.0
  eslint-config-prettier: ^9.1.0
  eslint-import-resolver-typescript: ^3.6.1
  eslint-plugin-header: ^3.1.1
  eslint-plugin-import: ^2.29.1
  eslint-plugin-jsx-a11y: ^6.9.0
  eslint-plugin-react: ^7.35.0
  eslint-plugin-react-hooks: ^4.6.2
  eslint-plugin-unused-imports: ^3.2.0
  fast-glob: ^3.3.2
  framer-motion: ^10.17.4
  handlebars: ^4.7.8
  happy-dom: ^14.12.3
  html2canvas: ^1.4.1
  husky: ^9.1.1
  js-yaml: ^4.1.0
  jsdom: ^24.1.1
  jspdf: ^2.5.1
  lint-staged: ^15.2.7
  ol: ^9.2.4
  ol-mapbox-style: ^12.3.4
  prettier: ^3.3.3
  proj4: ^2.9.0
  react: *react_version
  react-dom: *react_version
  react-icons: ^5.2.1
  react-select: ^5.8.0
  react-use: ^17.5.1
  resize-observer-polyfill: ^1.5.1
  rimraf: ^5.0.9
  sass: ^1.77.8
  tsx: ^4.16.2
  typedoc: ^0.26.5
  typescript: ~5.5.4
  uuid: ^10.0.0
  vite: ^5.4.8
  vite-plugin-eslint: ^1.8.1
  vitest: ^2.0.4
