packages:
  - src/**
  - "!**/test-data/**"
  - "!**/dist/**"

# https://pnpm.io/catalogs
catalog:
  # Trails core packages
  # https://github.com/open-pioneer/trails-core-packages
  "@open-pioneer/base-theme": ^4.4.0
  "@open-pioneer/core": ^4.4.0
  "@open-pioneer/http": ^4.4.0
  "@open-pioneer/integration": ^4.4.0
  "@open-pioneer/local-storage": ^4.4.0
  "@open-pioneer/notifier": ^4.4.0
  "@open-pioneer/react-utils": ^4.4.0
  "@open-pioneer/reactivity": ^4.4.0
  "@open-pioneer/runtime": ^4.4.0
  "@open-pioneer/test-utils": ^4.4.0
  "@open-pioneer/chakra-snippets": ^4.4.0

  "@chakra-ui/react": ^3.31.0
  "@chakra-ui/cli": ^3.31.0
  "@conterra/reactivity-core": ^0.8.1
  "@conterra/reactivity-events": ^0.8.1
  "@emotion/cache": ^11.14.0
  "@emotion/react": ^11.14.0
  "@emotion/styled": ^11.14.1
  "@formatjs/intl": ^4.1.0
  "@tanstack/react-table": ^8.21.3
  chakra-react-select: ^6.1.1
  classnames: ^2.5.1
  framer-motion: ^12.26.2
  html2canvas: ^1.4.1
  jspdf: ^4.1.0
  ol-mapbox-style: ^13.2.0
  ol: ^10.7.0
  proj4: ^2.20.2
  react-dom: ^19.2.3
  react-icons: ^5.5.0
  react-use: ^17.6.0
  react: ^19.2.3
  uuid: ^13.0.0

  # Devtools
  "@changesets/cli": "2.29.8"
  "@open-pioneer/build-package-cli": ^3.0.7
  "@open-pioneer/build-support": ^3.0.5
  "@open-pioneer/check-pnpm-duplicates": ^0.2.6
  "@open-pioneer/vite-plugin-pioneer": ^5.1.0
  "@testing-library/dom": ^10.4.1
  "@testing-library/jest-dom": ^6.9.1
  "@testing-library/react": ^16.3.1
  "@testing-library/user-event": ^14.6.1
  "@types/js-yaml": ^4.0.9
  "@types/jsdom": ^27.0.0
  "@types/node": ^20.19.30
  "@types/react": ^19.2.8
  "@types/react-dom": ^19.2.3
  "@typescript-eslint/parser": ^8.53.0
  "@vitejs/plugin-react-swc": ^4.2.2
  eslint: ^9.39.2
  "@eslint/js": ^9.39.2
  "typescript-eslint": ^8.53.0
  eslint-config-prettier: ^10.1.8
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-headers: ^1.3.3
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-unused-imports: ^4.3.0
  fast-glob: ^3.3.3
  handlebars: ^4.7.8
  happy-dom: ^20.3.1
  husky: ^9.1.7
  js-yaml: ^4.1.1
  jsdom: ^27.4.0
  lint-staged: ^16.2.7
  prettier: ^3.8.0
  resize-observer-polyfill: ^1.5.1
  rimraf: ^6.1.2
  sass: ^1.97.2
  tsx: ^4.21.0
  typedoc: ^0.28.16
  typescript: ^5.9.3
  vite: ^7.3.1
  vite-plugin-eslint: ^1.8.1
  vitest: ^4.0.17
  zx: ^8.8.5

auditConfig:
  ignoreCves: []

# Install older versions by default
resolutionMode: "lowest-direct"

# Configure a release cooldown
minimumReleaseAge: 4320 # 3 days in minutes
minimumReleaseAgeExclude:
  - "@open-pioneer/*"
  - "@conterra/*"
  - "jspdf@4.1.0"

overrides:
  # https://github.com/advisories/GHSA-v6h2-p8h4-qcjw
  "brace-expansion@>=1.0.0 <=1.1.11": "^1.1.12"
  "brace-expansion@>=2.0.0 <=2.0.1": "^2.0.2"

  # https://github.com/advisories/GHSA-52f5-9888-hmc6
  "tmp@<=0.2.3": "^0.2.4"

  # https://github.com/advisories/GHSA-mh29-5h37-fv8m
  "js-yaml@<3.14.2": "^3.14.2"

  # https://github.com/advisories/GHSA-5j98-mcp5-4vw2
  "glob@>=10.x <= 11.0.3": "^11.1.0"

  # We don't actually use the babel plugin.
  # The babel runtime is also not used as a production dependency.
  # See e.g. https://github.com/emotion-js/emotion/issues/2371
  "@emotion/react>@emotion/babel-plugin": "-"
  "@emotion/styled>@emotion/babel-plugin": "-"
  "@emotion/react>@babel/runtime": "-"
  "@emotion/styled>@babel/runtime": "-"

  # Just to get rid of some duplicate dependencies
  "source-map@<0.6.1": ">=0.6.1"
  "stylis@<4.3.5": ">= 4.3.5"
  "regenerator-runtime@<=0.13.11": "^0.14.0"
  "csstype@<3.2.3": ">=3.2.3"

  # Ensure patched packages have the expected version (patch was tested with this version):
  "@ark-ui/react": "5.30.0"
  "react-select": "5.10.2"
  "@zag-js/toast": "1.31.1"

allowUnusedPatches: true
ignorePatchFailures: false
patchedDependencies:
  # Ensure valids ids for aria-activedescendant and fix touch events in shadow DOM (see https://github.com/JedWatson/react-select/issues/5824)
  "react-select@*": "patches/react-select.patch"

  # Ensure all portals are mounted under `.pioneer-root` div
  "@ark-ui/react@*": "patches/@ark-ui__react.patch"

  # Fix display of toasts that are created before the Notifier UI is mounted
  # See https://github.com/chakra-ui/zag/issues/2922
  "@zag-js/toast": patches/@zag-js__toast.patch

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild

ignoredBuiltDependencies:
  # Seems to work without build scripts; may revisit later if actually needed.
  - core-js
  - unrs-resolver

# Workaround for current problems regarding our vite plugin + vite's optimizeDeps feature
shamefullyHoist: true

# Workspace root itself depends on runtime, and all packages (including runtime) have a dev dependency on workspace root
# for shared scripts.
ignoreWorkspaceCycles: true

linkWorkspacePackages: false
strictPeerDependencies: true
