packages:
  - src/**
  - "!**/test-data/**"
  - "!**/dist/**"
  - .

# Shared version expressions (yaml anchors).
# This is a yaml feature and is not interpreted by pnpm directly.
__versions:
  - &react_version ^19.1.0
  - &core_packages_version ^3.1.0

# https://pnpm.io/catalogs
catalog:
  # Trails core packages
  # https://github.com/open-pioneer/trails-core-packages
  "@open-pioneer/base-theme": *core_packages_version
  "@open-pioneer/chakra-integration": *core_packages_version
  "@open-pioneer/core": *core_packages_version
  "@open-pioneer/http": *core_packages_version
  "@open-pioneer/integration": *core_packages_version
  "@open-pioneer/local-storage": *core_packages_version
  "@open-pioneer/notifier": *core_packages_version
  "@open-pioneer/react-utils": *core_packages_version
  "@open-pioneer/reactivity": *core_packages_version
  "@open-pioneer/runtime": *core_packages_version
  "@open-pioneer/test-utils": *core_packages_version

  "@chakra-ui/icons": ^2.2.4
  "@chakra-ui/react": ^2.10.6
  "@conterra/reactivity-core": ^0.5.0
  "@emotion/cache": ^11.13.1
  "@emotion/react": ^11.13.3
  "@emotion/styled": ^11.13.0
  "@formatjs/intl": ^3.1.6
  "@tanstack/react-table": ^8.20.5
  chakra-react-select: ^5.0.4
  classnames: ^2.3.2
  framer-motion: ^12.9.1
  html2canvas: ^1.4.1
  jspdf: ^3.0.1
  ol-mapbox-style: ^12.4.1
  ol: ^10.5.0
  proj4: ^2.12.1
  react-dom: *react_version
  react-icons: ^5.3.0
  react-select: ^5.8.0
  react-use: ^17.5.1
  react: *react_version
  uuid: ^11.1.0

  # Devtools
  "@changesets/cli": 2.27.9
  "@open-pioneer/build-package-cli": ^3.0.1
  "@open-pioneer/build-support": ^3.0.1
  "@open-pioneer/check-pnpm-duplicates": ^0.2.1
  "@open-pioneer/vite-plugin-pioneer": ^4.0.1
  "@testing-library/dom": ^10.4.0
  "@testing-library/jest-dom": ^6.6.2
  "@testing-library/react": ^16.3.0
  "@testing-library/user-event": ^14.5.2
  "@types/js-yaml": ^4.0.9
  "@types/jsdom": ^21.1.7
  "@types/node": ^20.14.8
  "@types/proj4": "^2.5.2"
  "@types/react-dom": ^19.1.2
  "@types/react": ^19.1.2
  "@types/uuid": ^10.0.0
  "@typescript-eslint/eslint-plugin": ^8.31.0
  "@typescript-eslint/parser": ^8.31.0
  "@vitejs/plugin-react-swc": ^3.9.0
  eslint: ^8.57.1
  eslint-config-prettier: ^10.0.2
  eslint-import-resolver-typescript: ^4.3.4
  eslint-plugin-header: ^3.1.1
  eslint-plugin-import: ^2.31.0
  eslint-plugin-jsx-a11y: ^6.10.1
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-unused-imports: ^4.1.4
  fast-glob: ^3.3.3
  handlebars: ^4.7.8
  happy-dom: ^17.4.4
  husky: ^9.1.6
  js-yaml: ^4.1.0
  jsdom: ^26.0.0
  lint-staged: ^15.5.1
  prettier: ^3.5.3
  resize-observer-polyfill: ^1.5.1
  rimraf: ^6.0.1
  sass: ^1.87.0
  tsx: ^4.19.1
  typedoc: ^0.28.3
  typescript: ^5.8.3
  vite: ^6.3.3
  vite-plugin-eslint: ^1.8.1
  vitest: ^3.1.2

auditConfig:
  ignoreCves: []

overrides:
  # See patchedDependencies
  "@changesets/assemble-release-plan": "6.0.4"

  # https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
  "semver@<7.5.2": ">=7.5.2"
  # https://github.com/advisories/GHSA-72xf-g2v4-qvf3
  "tough-cookie@<4.1.3": ">=4.1.3"
  # https://github.com/advisories/GHSA-grv7-fg5c-xmjg
  "braces@<3.0.3": ">=3.0.3"
  # https://github.com/advisories/GHSA-3h5v-q93c-6h6q
  "ws@>=8.0.0 <8.17.1": ">=8.17.1"
  # https://github.com/advisories/GHSA-3q56-9cc2-46j4
  "fast-loops@<1.1.4": ">=1.1.4"
  # https://github.com/advisories/GHSA-952p-6rrq-rcjv
  "micromatch@<4.0.8": ">=4.0.8"
  # https://github.com/advisories/GHSA-gcx4-mw62-g8wm
  "vite-plugin-eslint>rollup": ">=3.29.5"
  # https://github.com/advisories/GHSA-3xgq-45jj-v275
  "cross-spawn@<7.0.5": ">=7.0.5"
  # https://github.com/advisories/GHSA-mwcw-c2x4-8c55
  "nanoid@<3.3.8": "^3.3.8"
  # CVE-2025-26791
  "dompurify@<3.2.4": ">=3.2.4"
  # https://github.com/advisories/GHSA-67mh-4wv8-2f99
  "esbuild@<0.25.0": ">=0.25.0"
  # https://github.com/advisories/GHSA-v2mw-5mch-w8c5
  "canvg@<=4.0.2": ">=4.0.3"
  # https://github.com/advisories/GHSA-968p-4wvh-cqc8
  "@babel/runtime": ">=7.26.10"

patchedDependencies:
  # Don't bump major if peerDep has a minor release. see https://github.com/changesets/changesets/pull/1132
  # NOTE: Also in overrides to pin the version.
  "@changesets/assemble-release-plan@6.0.4": "patches/@changesets__assemble-release-plan.patch"

  # Ensure valids ids for aria-activedescendant and fix touch events in shadow DOM (see https://github.com/JedWatson/react-select/issues/5824)
  "react-select": "patches/react-select.patch"
  # Outside click detection for menus and other popovers (see https://github.com/open-pioneer/trails-openlayers-base-packages/issues/184)
  "@chakra-ui/hooks": "patches/@chakra-ui__hooks.patch"

dangerouslyAllowAllBuilds: false
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild

ignoredBuiltDependencies:
  # Seems to work without build scripts; may revisit later if actually needed.
  - core-js
  - unrs-resolver

# Don't automatically link to workspace packages (use e.g. "workspace:^" instead).
linkWorkspacePackages: false
autoInstallPeers: true
dedupePeerDependents: true
strictPeerDependencies: true

# Workaround for current problems regarding our vite plugin + vite's optimizeDeps feature
shamefullyHoist: true

# Workspace root itself depends on runtime, and all packages (including runtime) have a dev dependency on workspace root
# for shared scripts.
ignoreWorkspaceCycles: true
