packages:
  - src/**
  - "!**/test-data/**"
  - "!**/dist/**"
  - .

# https://pnpm.io/catalogs
catalog:
  # Trails core packages
  # https://github.com/open-pioneer/trails-core-packages
  "@open-pioneer/base-theme": ^4.0.0
  "@open-pioneer/core": ^4.0.0
  "@open-pioneer/http": ^4.0.0
  "@open-pioneer/integration": ^4.0.0
  "@open-pioneer/local-storage": ^4.0.0
  "@open-pioneer/notifier": ^4.0.0
  "@open-pioneer/react-utils": ^4.0.0
  "@open-pioneer/reactivity": ^4.0.0
  "@open-pioneer/runtime": ^4.0.0
  "@open-pioneer/test-utils": ^4.0.0
  "@open-pioneer/chakra-snippets": ^4.0.0

  "@chakra-ui/react": ^3.21.1
  "@chakra-ui/cli": ^3.21.1
  "@conterra/reactivity-core": ^0.7.0
  "@emotion/cache": ^11.14.0
  "@emotion/react": ^11.14.0
  "@emotion/styled": ^11.14.0
  "@formatjs/intl": ^3.1.6
  "@tanstack/react-table": ^8.21.3
  chakra-react-select: ^6.1.0
  classnames: ^2.5.1
  framer-motion: ^12.16.0
  html2canvas: ^1.4.1
  jspdf: ^3.0.1
  ol-mapbox-style: ^13.0.1
  ol: ^10.5.0
  proj4: ^2.17.0
  react-dom: ^19.1.0
  react-icons: ^5.5.0
  react-use: ^17.6.0
  react: ^19.1.0
  uuid: ^11.1.0

  # Devtools
  "@changesets/cli": 2.27.9
  "@open-pioneer/build-package-cli": ^3.0.2
  "@open-pioneer/build-support": ^3.0.2
  "@open-pioneer/check-pnpm-duplicates": ^0.2.2
  "@open-pioneer/vite-plugin-pioneer": ^4.0.2
  "@testing-library/dom": ^10.4.0
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^16.3.0
  "@testing-library/user-event": ^14.6.1
  "@types/js-yaml": ^4.0.9
  "@types/jsdom": ^21.1.7
  "@types/node": ^20.19.0
  "@types/proj4": "^2.5.6"
  "@types/react": ^19.1.6
  "@types/react-dom": ^19.1.6
  "@types/uuid": ^10.0.0
  "@typescript-eslint/eslint-plugin": ^8.33.1
  "@typescript-eslint/parser": ^8.33.1
  "@vitejs/plugin-react-swc": ^3.10.1
  eslint: ^8.57.1
  eslint-config-prettier: ^10.1.5
  eslint-import-resolver-typescript: ^4.4.3
  eslint-plugin-header: ^3.1.1
  eslint-plugin-import: ^2.31.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-unused-imports: ^4.1.4
  fast-glob: ^3.3.3
  handlebars: ^4.7.8
  happy-dom: ^17.6.3
  husky: ^9.1.7
  js-yaml: ^4.1.0
  jsdom: ^26.1.0
  lint-staged: ^16.1.0
  prettier: ^3.5.3
  resize-observer-polyfill: ^1.5.1
  rimraf: ^6.0.1
  sass: ^1.89.1
  tsx: ^4.19.4
  typedoc: ^0.28.5
  typescript: ^5.8.3
  vite: ^6.3.5
  vite-plugin-eslint: ^1.8.1
  vitest: ^3.2.2
  zx: ^8.5.5

auditConfig:
  ignoreCves: []

overrides:
  # https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
  "semver@<7.5.2": ">=7.5.2"
  # https://github.com/advisories/GHSA-72xf-g2v4-qvf3
  "tough-cookie@<4.1.3": ">=4.1.3"
  # https://github.com/advisories/GHSA-grv7-fg5c-xmjg
  "braces@<3.0.3": ">=3.0.3"
  # https://github.com/advisories/GHSA-3h5v-q93c-6h6q
  "ws@>=8.0.0 <8.17.1": ">=8.17.1"
  # https://github.com/advisories/GHSA-3q56-9cc2-46j4
  "fast-loops@<1.1.4": ">=1.1.4"
  # https://github.com/advisories/GHSA-952p-6rrq-rcjv
  "micromatch@<4.0.8": ">=4.0.8"
  # https://github.com/advisories/GHSA-gcx4-mw62-g8wm
  "vite-plugin-eslint>rollup": ">=3.29.5"
  # https://github.com/advisories/GHSA-3xgq-45jj-v275
  "cross-spawn@<7.0.5": ">=7.0.5"
  # https://github.com/advisories/GHSA-mwcw-c2x4-8c55
  "nanoid@<3.3.8": "^3.3.8"
  # CVE-2025-26791
  "dompurify@<3.2.4": ">=3.2.4"
  # https://github.com/advisories/GHSA-67mh-4wv8-2f99
  "esbuild@<0.25.0": ">=0.25.0"
  # https://github.com/advisories/GHSA-v2mw-5mch-w8c5
  "canvg@<=4.0.2": ">=4.0.3"
  # https://github.com/advisories/GHSA-968p-4wvh-cqc8
  "@babel/runtime": ">=7.26.10"
  # https://github.com/advisories/GHSA-v6h2-p8h4-qcjw
  "brace-expansion@>=1.0.0 <=1.1.11": "^1.1.12"
  "brace-expansion@>=2.0.0 <=2.0.1": "^2.0.2"

  # Just to get rid of some duplicate dependencies
  "source-map@<0.6.1": ">=0.6.1"
  "stylis@<4.3.5": ">= 4.3.5"

ignorePatchFailures: false
patchedDependencies:
  # Ensure valids ids for aria-activedescendant and fix touch events in shadow DOM (see https://github.com/JedWatson/react-select/issues/5824)
  "react-select": "patches/react-select.patch"

  # - Ensure all portals are mounted under `.pioneer-root` div
  "@ark-ui/react@*": "patches/@ark-ui__react.patch"

dangerouslyAllowAllBuilds: false
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild

ignoredBuiltDependencies:
  # Seems to work without build scripts; may revisit later if actually needed.
  - core-js
  - unrs-resolver

# Don't automatically link to workspace packages (use e.g. "workspace:^" instead).
linkWorkspacePackages: false
autoInstallPeers: true
dedupePeerDependents: true
strictPeerDependencies: true

# Workaround for current problems regarding our vite plugin + vite's optimizeDeps feature
shamefullyHoist: true

# Workspace root itself depends on runtime, and all packages (including runtime) have a dev dependency on workspace root
# for shared scripts.
ignoreWorkspaceCycles: true
