name: open-pioneer-trails-secman-ogc-sample
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./trails-realm.json:/opt/keycloak/data/import/trails-realm.json
  identity:
    image: acrctprdeng.azurecr.io/identity-service:1.5.0
    container_name: identity
    ports:
      - "8081:8080"
    environment:
      - CONTEXT_PATH=identity
      - LOGGING_LOGGER_LEVEL=DEBUG
      - SECURITY_SESSION_ENFORCESECUREANDSAMESITENONE=false
      - SECURITY_SESSION_COOKIEDOMAIN=
      - SECURITY_OAUTH_PROVIDER=keycloak
      - SECURITY_OAUTH_PROVIDER_KEYCLOAK_URL=http://mylocalhost:8080/
      - SECURITY_OAUTH_PROVIDER_KEYCLOAK_REALM=trails
      - SECURITY_OAUTH_CLIENTID=identity-service
      - SECURITY_OAUTH_CLIENTSECRET=Ya7A9txIVFsbwhfB9sQKxOtAinQYV776
      - SECURITY_OAUTH_TOKENRULES=http://mylocalhost:8080,ACCESS_TOKEN
      - CORS_ANY_ORIGINS=true
      - SECURITY_SSL_TRUSTANY=true
    depends_on:
      - keycloak
    extra_hosts:
      # NOTE: please add a `mylocalhost` entry in the system `hosts` file
      - "mylocalhost:host-gateway"
  secman-ogc:
    image: acrctprdeng.azurecr.io/securitymanager-ogc:0.1.1
    container_name: secman-ogc
    ports:
      - "8082:8080"
    environment:
      - SECURITY_MODE=IDENTITY
      - SECURITY_IDENTITY_SELF_SERVICE_URL=http://mylocalhost:8081/identity/account/self
      - CORS_ANY_ORIGINS=true
    depends_on:
      - identity
    volumes:
      - ./secman-ogc:/app/conf/server
    extra_hosts:
      # NOTE: please add a `mylocalhost` entry in the system `hosts` file
      - "mylocalhost:host-gateway"
