#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '--- run linting --- '
pnpm lint

echo '--- run prettier ---'
pnpm prettier-check

echo '--- run typescript check ---'
pnpm check-types

echo '--- run tests ---'
pnpm test-plugin
pnpm -- vitest run
