# Checks dependencies for security vulnerabilities.
name: Audit dependencies (weekly)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1"

permissions:
  contents: read

jobs:
  audit-dependencies:
    uses: open-pioneer/trails-repo-automation/.github/workflows/shared-audit-dependencies.yml@038ec2c85b78d22432bf0264f74a6544278f71f3 # main
