name: Audit dependencies (daily)

on:
  workflow_dispatch:

  schedule:
    - cron: "0 12 * * 1"

permissions:
  contents: read

jobs:
  audit-dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install
        uses: open-pioneer/trails-repo-automation/.github/actions/install@main
      - name: Audit dependencies
        run: pnpm audit
