name: Audit dependencies (daily)

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  audit-dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Install
        uses: open-pioneer/trails-repo-automation/.github/actions/install@417c824a6aab4deea1edaa18e3a8b16f94c44594 # main
      - name: Audit dependencies
        run: pnpm audit
