name: Audit dependencies (daily)

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  audit-dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/install
      - name: Audit dependencies
        run: pnpm audit
