# Moves new issues to the maintenance board so they that are not missed by the team.
name: Add new issues to maintenance board

on:
  issues:
    types:
      - opened
      - reopened
      - transferred

permissions:
  contents: read

jobs:
  add-to-board:
    uses: open-pioneer/trails-repo-automation/.github/workflows/shared-new-issue.yml@038ec2c85b78d22432bf0264f74a6544278f71f3 # main
    secrets:
      ISSUE_AUTOMATION_TOKEN: ${{ secrets.ISSUE_AUTOMATION_TOKEN }}
