# Deploys a preview for every pull request.
name: Preview PR

on:
  workflow_run:
    workflows:
      - Build Samples
    types:
      - completed

permissions:
  contents: read

jobs:
  preview:
    name: Preview PR
    uses: open-pioneer/trails-repo-automation/.github/workflows/shared-preview-pr.yml@main
    permissions:
      actions: read
      contents: read
      pull-requests: write
    with:
      demo-id: openlayers-base-packages
    secrets:
      DEMO_DEPLOY_TOKEN: ${{ secrets.DEMO_DEPLOY_TOKEN }}
