# Publishes x.y.z-dev* package versions for packages in this repository.
name: Publish snapshot

on:
  workflow_dispatch:
    inputs:
      snapshot-tag:
        type: string
        description: Name of the snapshot build tag. Use "dev" for the main branch and "dev-XYZ" for other branches.
        default: dev
        required: true

permissions:
  contents: read

jobs:
  publish-snapshot:
    uses: open-pioneer/trails-repo-automation/.github/workflows/shared-publish-snapshot.yml@main
    with:
      snapshot-tag: ${{ inputs.snapshot-tag }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
